# Only one controller for the robot
crom:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Arm controller Left      ------------------------------------
  torso_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - waist_joint
      - head_pan_joint
      - head_tilt_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint

  gazebo_ros_control/pid_gains: # Required because we're controlling an effort interface
      waist_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 3000}
      head_pan_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      head_tilt_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      left_arm_1_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      left_arm_1_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      left_arm_2_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      left_arm_3_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      left_arm_4_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      left_arm_5_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      left_arm_6_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      right_arm_1_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      right_arm_2_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      right_arm_3_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      right_arm_4_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      right_arm_5_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
      right_arm_6_joint: {d: 1, i: 1, i_clamp: 1, i_clamp_max: 1.0, i_clamp_min: 0.0, p: 100}
